CAF-2999: Marathon Production templates
caf-archive/job-service-deploy pull request #3
Opened 2017-06-01 17:49 UTC by arogan92

2017-06-01 19:26 UTC, mulhollandc requested changes

2017-06-01 19:26 UTC, mulhollandc commented on production-marathon/README.md
> +The Production Marathon deployment supports the deployment of the CAF Job Service on Mesos/Marathon. This folder contains the marathon environment and template files that are required to deploy the s
Drop CAF from CAF Job Service. Likewise throughout remainder of document as I think it is referred to as just the Job Service in other documentation. You may also wish to mention that both the job service and job tracking worker is deployed.

2017-06-01 19:26 UTC, mulhollandc commented on production-marathon/README.md
> +The `marathon.json.b` template file describes the marathon deployment information required for Job Service. The template file uses property substitution to get values for configurable properties **re
Required for both Job Service and Job Tracking Worker.

2017-06-01 19:26 UTC, mulhollandc commented on production-marathon/README.md
> +- `DOCKER_REGISTRY`: This setting configures the docker repository that the Job Service image will be pulled from.
Again not just the Job Service image.

2017-06-01 19:26 UTC, mulhollandc commented on production-marathon/README.md
> +	- **Default Values:**
Are these the minimum values we can get away with? Same goes for memory? I only ask because Dermot mentioned this during storytime.

2017-06-01 19:26 UTC, mulhollandc commented on production-marathon/marathon.env
> +export DOCKER_REGISTRY=NOT_SET_QA_index.docker.io/jobservice
The suffix after NOT_SET_ should match the actual setting as far as I understand. For example, NOT_SET_DOCKER_REGISTRY

2017-06-01 19:26 UTC, mulhollandc commented on production-marathon/marathon.json.b
> +								"servicePort": 9330
These service ports should be configurable I would have thought?

2017-06-02 10:00 UTC, arogan92 commented on production-marathon/README.md
> +	- **Default Values:**
I pulled the previous values from the docker-compose file in job-service deploy. However speaking with Greg and in keeping with consistency across the deployment stages I've upped the minimum specs to what he has in his production compose file (I'll add the commit in after this comment). He deem's these sufficient for minimum specs

2017-06-02 10:51 UTC, arogan92 commented
Updates made after pull request comments

2017-06-02 11:08 UTC, mulhollandc commented on production-marathon/README.md
> +The Production Marathon deployment supports the deployment of the Job Service on Mesos/Marathon. This folder contains the marathon environment and template files that are required to deploy both the
Job Tracking Worker. Same goes for any further references to Job Tracking in the README.

2017-06-02 11:08 UTC, mulhollandc commented on production-marathon/README.md
> +The `marathon.json.b` template file describes the marathon deployment information required for starting both the Job Service and Job Tracking workers. The template file uses property substitution to
and Job Tracking Worker.

2017-06-02 11:08 UTC, mulhollandc commented on production-marathon/marathon.env
> +export DOCKER_REGISTRY=NOT_SET_DOCKER_REGISTRY
The contents of this environment file could possibly change today depending on any further perl command changes.

2017-06-02 11:22 UTC, arogan92 commented on production-marathon/marathon.env
> +export DOCKER_REGISTRY=NOT_SET_DOCKER_REGISTRY
Speaking with Andy there, the documentation and the standard set out for the environment variables is good.  The command for setting these and property substitution needs fixing.

I'm going to take a look at the command now and see if I can solve it. I suppose the README here if it's good to go can be merged in and the command at the bottom updated once a fix is found just simply update the documentation afterwards?

2017-06-02 11:22 UTC, arogan92 commented
Changes made after  further comments on readme

2017-06-02 13:17 UTC, mulhollandc approved these changes

2017-06-02 13:18 UTC, merged